import React, { useState, useEffect, useMemo } from 'react';
import { Plus, Trash2, Crown, AlertCircle } from 'lucide-react';
import { Button, Input, Select, Card } from './UI';
import { Entry, Service, ServiceItem, VIPMember } from '../types';
import { calculateVIPStatus, formatCurrency, getTodayISO } from '../services/utils';

interface EntryTabProps {
  services: Service[];
  staff: string[];
  vips: VIPMember[];
  entries: Entry[];
  onSave: (entry: Entry) => void;
  onAddVIP: (vip: VIPMember) => void;
}

export const EntryTab: React.FC<EntryTabProps> = ({ services, staff, vips, entries, onSave, onAddVIP }) => {
  const [phone, setPhone] = useState('');
  const [name, setName] = useState('');
  const [selectedStaff, setSelectedStaff] = useState('');
  const [date, setDate] = useState(getTodayISO());
  const [serviceRows, setServiceRows] = useState<ServiceItem[]>([{ name: '', amount: 0 }]);
  // Discount is now calculated, not manual percentage for VIPs
  const [manualDiscount, setManualDiscount] = useState<number>(0);
  
  // VIP Detection
  const vipStatus = useMemo(() => calculateVIPStatus(phone, vips), [phone, vips]);
  const existingVip = useMemo(() => vips.find(v => v.phone === phone), [phone, vips]);

  // Auto-fill name if exists in history
  useEffect(() => {
    if (phone.length > 3) {
      const lastEntry = [...entries]
        .filter(e => e.phone === phone)
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
      
      if (lastEntry) setName(lastEntry.name);
      else if (existingVip) setName(existingVip.name);
    }
  }, [phone, entries, existingVip]);

  const handleAddRow = () => {
    setServiceRows([...serviceRows, { name: '', amount: 0 }]);
  };

  const handleRemoveRow = (index: number) => {
    const newRows = [...serviceRows];
    newRows.splice(index, 1);
    setServiceRows(newRows);
  };

  const handleServiceChange = (index: number, serviceName: string) => {
    const newRows = [...serviceRows];
    const service = services.find(s => s.name === serviceName);
    newRows[index] = { 
      name: serviceName, 
      amount: service ? service.amount : 0 
    };
    setServiceRows(newRows);
  };

  const handleAmountChange = (index: number, amount: number) => {
    const newRows = [...serviceRows];
    newRows[index].amount = amount;
    setServiceRows(newRows);
  };

  // --- NEW LOGIC: VIP Discount ---
  const calculation = useMemo(() => {
    let subtotal = 0;
    let vipSavings = 0;

    serviceRows.forEach(item => {
        const amt = item.amount || 0;
        subtotal += amt;
        
        // VIP Rule: 20% off ONLY if service amount > 100
        if (vipStatus === 'active' && amt > 100) {
            vipSavings += amt * 0.20;
        }
    });

    // If VIP active, we ignore manual discount to enforce rule, OR we can allow it on top.
    // Prompt: "make it so that the 20% off for vips is only for the services above 100rs"
    // This implies strictly replacing the old logic.
    // If NOT VIP, use manual discount.
    let finalDiscountAmount = 0;
    if (vipStatus === 'active') {
        finalDiscountAmount = vipSavings;
    } else {
        finalDiscountAmount = subtotal * (manualDiscount / 100);
    }

    const totalPaid = Math.max(0, subtotal - finalDiscountAmount);
    return { subtotal, finalDiscountAmount, totalPaid };
  }, [serviceRows, vipStatus, manualDiscount]);


  const handleSave = () => {
    if (!phone || !name || !selectedStaff) {
      alert("Please fill in Phone, Name and Staff.");
      return;
    }
    const validServices = serviceRows.filter(s => s.name && s.amount > 0);
    if (validServices.length === 0) {
      alert("Please add at least one valid service.");
      return;
    }

    const newEntry: Entry = {
      id: '', // Generated by Firestore
      date,
      datetime: new Date().toISOString(),
      phone,
      name,
      staff: selectedStaff,
      services: validServices,
      total: calculation.subtotal,
      // Store effective discount percentage or amount? 
      // Type is 'number'. Let's store the amount here for better record keeping 
      // OR store percentage equivalent. Let's store amount and assume UI handles it,
      // but 'Entry' interface usually expects percentage in the original code. 
      // To keep it simple, we store the *saved amount* in `discount` field if VIP, or % if manual.
      // Actually, keeping consistency: store percentage equivalent to make Reports tab look ok?
      // No, let's store the raw discount amount in `discount` field but logic in Reports uses it as %.
      // Wait, original code: `paid = subtotal - (subtotal * discount / 100)`.
      // If I store amount, reports might break. 
      // Solution: Add a flag or just calculate percentage:
      discount: calculation.subtotal > 0 ? Number(((calculation.finalDiscountAmount / calculation.subtotal) * 100).toFixed(2)) : 0,
      paid: calculation.totalPaid,
      memberStatus: vipStatus
    };

    onSave(newEntry);
    
    // Reset Form
    setPhone('');
    setName('');
    setSelectedStaff('');
    setServiceRows([{ name: '', amount: 0 }]);
    setManualDiscount(0);
  };

  const handleQuickAddVIP = () => {
    if (!phone || !name) return alert("Enter name and phone first");
    const newVip: VIPMember = {
      phone,
      name,
      date: getTodayISO(),
      staff: selectedStaff || 'Unknown'
    };
    onAddVIP(newVip);
  };

  // Filter today's entries for the quick view
  const todaysEntries = useMemo(() => 
    entries
      .filter(e => e.date === getTodayISO())
      // @ts-ignore: Sort by timestamp if available or ID
      .sort((a,b) => (b.timestamp || 0) - (a.timestamp || 0)),
    [entries]
  );

  return (
    <div className="space-y-6">
      <Card title="New Entry">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <div className="relative">
            <Input 
              label="Phone Number" 
              value={phone} 
              onChange={e => setPhone(e.target.value)} 
              placeholder="98765..." 
            />
            {vipStatus === 'active' && (
              <span className="absolute top-0 right-0 mt-1 mr-1 text-xs font-bold text-teal-600 flex items-center gap-1">
                <Crown size={12} /> VIP Member
              </span>
            )}
            {vipStatus === 'expired' && (
              <span className="absolute top-0 right-0 mt-1 mr-1 text-xs font-bold text-red-600 flex items-center gap-1">
                <AlertCircle size={12} /> VIP Expired
              </span>
            )}
          </div>
          <Input 
            label="Client Name" 
            value={name} 
            onChange={e => setName(e.target.value)} 
            placeholder="Client Name" 
          />
          <Select 
            label="Staff" 
            value={selectedStaff} 
            onChange={e => setSelectedStaff(e.target.value)}
          >
            <option value="">Select Staff</option>
            {staff.map(s => <option key={s} value={s}>{s}</option>)}
          </Select>
          <Input 
            label="Date" 
            type="date" 
            value={date} 
            onChange={e => setDate(e.target.value)} 
          />
        </div>

        <div className="mb-4">
            <div className="flex justify-between items-center mb-2">
                <label className="text-sm font-semibold text-slate-600">Services</label>
                <Button size="sm" variant="ghost" onClick={handleAddRow}><Plus size={16} /> Add Service</Button>
            </div>
            <div className="space-y-3">
                {serviceRows.map((row, index) => (
                    <div key={index} className="flex gap-3 items-center">
                        <div className="flex-grow">
                             <Select 
                                value={row.name} 
                                onChange={e => handleServiceChange(index, e.target.value)}
                                className="w-full"
                            >
                                <option value="">Select Service</option>
                                {services.map(s => <option key={s.name} value={s.name}>{s.name}</option>)}
                            </Select>
                        </div>
                        <div className="w-32">
                             <Input 
                                type="number" 
                                value={row.amount || ''} 
                                onChange={e => handleAmountChange(index, parseFloat(e.target.value))}
                                placeholder="0.00"
                            />
                        </div>
                        <button 
                            onClick={() => handleRemoveRow(index)}
                            className="text-slate-400 hover:text-red-500 p-2"
                        >
                            <Trash2 size={18} />
                        </button>
                    </div>
                ))}
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-end border-t border-slate-100 pt-6">
           <div className="flex gap-4">
             {(!existingVip && phone && name) && (
                 <Button variant="secondary" onClick={handleQuickAddVIP} className="bg-yellow-50 border-yellow-200 text-yellow-700 hover:bg-yellow-100">
                    <Crown size={16} className="mr-2" /> Make VIP
                 </Button>
             )}
           </div>
           <div className="space-y-3">
             <div className="flex items-center justify-between">
                <label className="text-sm font-medium text-slate-600">Subtotal</label>
                <span className="font-semibold">{formatCurrency(calculation.subtotal)}</span>
             </div>
             
             {/* Show Discount Input only if NOT VIP */}
             {vipStatus !== 'active' ? (
                <div className="flex items-center justify-between gap-4">
                    <label className="text-sm font-medium text-slate-600">Manual Discount (%)</label>
                    <Input 
                        type="number" 
                        className="w-24 text-right" 
                        value={manualDiscount} 
                        onChange={e => setManualDiscount(parseFloat(e.target.value) || 0)} 
                    />
                </div>
             ) : (
                <div className="flex items-center justify-between text-teal-600 bg-teal-50 px-3 py-2 rounded-lg text-sm">
                    <span className="flex items-center gap-2"><Crown size={14}/> VIP Savings (20% off)</span>
                    <span className="font-bold">-{formatCurrency(calculation.finalDiscountAmount)}</span>
                </div>
             )}

             <div className="flex items-center justify-between text-lg font-bold text-teal-700 bg-teal-50 p-3 rounded-xl border border-teal-100">
                <span>Total to Pay</span>
                <span>{formatCurrency(calculation.totalPaid)}</span>
             </div>
             <Button onClick={handleSave} className="w-full" disabled={!phone || !name || !selectedStaff}>
                Save Entry
             </Button>
           </div>
        </div>
      </Card>

      <Card title="Today's Entries">
        {todaysEntries.length === 0 ? (
            <p className="text-slate-500 text-sm">No entries yet today.</p>
        ) : (
            <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                    <thead className="bg-slate-50 text-slate-600">
                        <tr>
                            <th className="p-3 rounded-tl-lg">Time</th>
                            <th className="p-3">Client</th>
                            <th className="p-3">Services</th>
                            <th className="p-3">Staff</th>
                            <th className="p-3 text-right rounded-tr-lg">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {todaysEntries.map(entry => (
                            <tr key={entry.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50">
                                <td className="p-3 text-slate-500">
                                    {new Date(entry.datetime).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                                </td>
                                <td className="p-3 font-medium">
                                    {entry.name} <br/>
                                    <span className="text-xs text-slate-400">{entry.phone}</span>
                                </td>
                                <td className="p-3 text-slate-600">
                                    {entry.services.map(s => s.name).join(', ')}
                                </td>
                                <td className="p-3 text-slate-600">{entry.staff}</td>
                                <td className="p-3 text-right font-bold text-slate-700">{formatCurrency(entry.paid)}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        )}
      </Card>
    </div>
  );
};
